### ISSUE TITLE
Bug with meta enchant

### ISSUE THREAD

**Issue by SaphiLC** [ABravePanda/LootCrate#10]
The autocomplete with tab says enchantment and autocompletes the spells, if i do something wrong, the chat says i have to use enchant instead of enchantment, i think its a typo ^^

A way to remove enchantments would be nice too

**Comment by ABravePanda** [comment]
Fixed with this [commit](https://github.com/ABravePanda/LootCrate/commit/9181c8623e961c10f2e813b615e24e09f8750cd2). Thank you for bringing it to my attention.

I will add the remove enchantment command in a future update, thanks for the idea as well.
