### ISSUE TITLE
Belohnungen werden nicht ins Inventar gelegt 

### ISSUE THREAD

**Issue by BuftiCrfati** [ABravePanda/LootCrate#11]
hey ich habe das Problem das Belohnungen nicht ins Inventar gelegt werden. wäre schön wenn man mir da helfen kann

**Comment by ABravePanda** [comment]
Translation to English: "Hey, I have the problem that the rewards are not put into my inventory. would be nice if you can help me there"
-----------------------------------------------------------------------------

English: Look here for the solution to your problem, https://github.com/ABravePanda/LootCrate/wiki/Frequently-Asked-Questions-(FAQ), if that doesn't help please reply here!

German: Suchen Sie hier nach der Lösung für Ihr Problem, https://github.com/ABravePanda/LootCrate/wiki/Frequently-Asked-Questions-(FAQ), wenn das nicht hilft, antworten Sie bitte hier!

**Comment by BuftiCrfati** [comment]
danke das hat geklappt.

jetzt hab ich das Problem das einige Items nicht gehen und da hat man dann ein leeren Slots wo man nix bekommt. was kann man da machen ? weil ich möchte nicht ständig ne neue lootchest erstellen
