### ISSUE TITLE
Crates created doesn't load when starting the server

### ISSUE THREAD

**Issue by TonyMontero** [ABravePanda/LootCrate#12]
Hey there! Loving your plugin!
When I load up the plugin nothing weird shows up and everything's fine but not a single crate loads up. After that the crates won't work until I do a Lootcrate reload. Then the crates work again.

- Server: Purpur (build 1331)
- Minecraft: 1.17.1
- Plugin ver.: 0.4.2

After a **lootcrate reload**, crates will work again

**Comment by ABravePanda** [comment]
Is the issue still persisting?
