### ISSUE TITLE
can not open crate even with permissions. 1.17.1

### ISSUE THREAD

**Issue by Trickyricky89** [ABravePanda/LootCrate#14]
players can not open the crate. even with the right permissions. they right click and nuthing at all happens but they can left click to look

**Comment by y0rqn** [comment]
i have the same issue here

**Comment by y0rqn** [comment]
only people with OP can open the chest

**Comment by VansNagpal** [comment]
Why Only Op can open I also have same issue

**Comment by ABravePanda** [comment]
What version are you using and can u send me the permission you gave them?

**Comment by y0rqn** [comment]
I fixed it after a long session of searching for the right commands and
perms. But thanks for your fast response :)

Op za 4 dec. 2021 18:01 schreef ABravePanda ***@***.***>:

**Comment by DreoNoux** [comment]
Can you share what you did? I cant get help via. discord

**Comment by ABravePanda** [comment]
> Can you share what you did? I cant get help via. discord

It should be "lootcrate.interact.[crateID]"

**Comment by ABravePanda** [comment]
Try turning of spawn protection as well. This has been an issue
