### ISSUE TITLE
shift+rightclick

### ISSUE THREAD

**Issue by Tmdoofking** [ABravePanda/LootCrate#15]
when you use none style if player open crate with shift+right click they could open chest/enderchest

**Comment by ABravePanda** [comment]
Im unable to reproduce this issue, what version of the plugin are you using?

**Comment by STEVE1010101** [comment]
latest version on spigotmc
paper 1.18.1

**Comment by ABravePanda** [comment]
can you share a video or something of the sorts. im still unable to reproduce this

**Comment by STEVE1010101** [comment]
https://youtu.be/4VrbhEBre18
here :)
