### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by dkbay** [ABravePanda/LootCrate#17]
It would be nice if there was a setting to decide how crates are sorted.

Atm they're sorted by chance (Correct me if I'm wrong)
Would also be nice to be able to sort by ID so we can change the ID in the file and get whatever order we prefer.

For example I'd prefer this order:
![image](https://user-images.githubusercontent.com/1548975/155898076-15bf6745-178b-476e-9819-001b230a8dfe.png)

But how it works with chance sorting it ends up looking like this.
![image](https://user-images.githubusercontent.com/1548975/155898079-f688c19a-6fbd-4a11-bd5a-13ac052f66b7.png)

**Comment by ABravePanda** [comment]
Thats a really good idea, thank you for the input! Will add it to the TODO list. 

I can add:
Sort by chance
Sort by name
Sort by id

Any other ideas?

**Comment by dkbay** [comment]
Could also sort by amount of items however I'm not sure how useful that would be.

**Comment by ABravePanda** [comment]
Added in newest update
