### ISSUE TITLE
What's the exact command to give everyone permission to open crates?

### ISSUE THREAD

**Issue by Link71112** [ABravePanda/LootCrate#34]
I've been running a few minehut mechanic tests in which I was testing the lootcrates. I found that my players could not open them, and checked the wiki. It says the command is "lootcrate.interact.*" but where do I put this in? I installed luckperms, that didn't work, and I can't put it in as a chat command nor a /<command> slash command.

**Comment by TaakoOfficial** [comment]
That's not the command, they the permission you need to give for default user group in luckperms
