### ISSUE TITLE
I can not give people perms to open crates

### ISSUE THREAD

**Issue by AxoGamer** [ABravePanda/LootCrate#39]
I can not give people perms to open crates. When i do the command (lootcrate.interact.* or lootcrate.interact.<crateID> it gives an error.
Server info:
I tried it on a 1.16.5, 1.17 and 1.17.1, 1.18.1,2,3 and 1.19+1.19.1 server but nothing worked
I tried it on a paper and spigot server

**Comment by TaakoOfficial** [comment]
Are you using a permissions plugin like luckperms?

**Comment by AxoGamer** [comment]
Yes

**Comment by AxoGamer** [comment]
Ok i finally found out how to give people perms, but now they can not do /lootcrate claim

**Comment by TylBurxyz** [comment]
> Ok i finally found out how to give people perms, but now they can not do /lootcrate claim

lootcrate.command.lootcrate.claim

**Comment by AxoGamer** [comment]
Ty
