### ISSUE TITLE
Give key after voting.

### ISSUE THREAD

**Issue by yensdecoster** [ABravePanda/LootCrate#4]
Hey there,

So i've recently installed your plugin with the idea to give a key after voting. Though, for some reason the commands to give a key don't work when send through the console. I've done some reading on your page and it sais you updated the plugin to allow console send commands. 

I used [lootcrate give [user] [id] [amount] to give a key using the console and I get an error saying: 
![image](https://user-images.githubusercontent.com/16511382/106187456-f69e4e00-61a5-11eb-8407-6355045158bb.png)

Any ideas?
Thanks

**Comment by ABravePanda** [comment]
I really do apologize that this is happening. I will get to work on it right now and release a patch. I very much appreciate you informing me!

**Comment by ABravePanda** [comment]
After reading your stack trace, you seem to be on an out of date version. Please upgrade to version 0.2.4 found on the spigot page https://www.spigotmc.org/resources/lootcrate-server-crate-plugin-1-16-x-server-must-have-free.87046/

**Comment by yensdecoster** [comment]
Ahhh thx, how did I not notice.
Thx for the quick reply :)

**Comment by ABravePanda** [comment]
If the issue persists after the update, feel free to open a new issue :)
