### ISSUE TITLE
Suddenly crates don't give prizes.

### ISSUE THREAD

**Issue by Derpydoo** [ABravePanda/LootCrate#51]
Crates have been working fine, but for some reason today nobody (myself included) can get anything out of the crates. You use the key, the animation plays, it says you've won an item but nothing appears in your inventory. /lootcrate reload didn't fix it, and I've tried making a new crate and that didn't work either. Not sure what caused this.

The only thing I changed were the permissions to use the crates and use the claim key menu. Used luckperms and lootcrate.command.lootcrate.claim, along with lootcrate.interact.*

**Comment by ABravePanda** [comment]
Did you set "isDisplay" to false or true for the items? Double check you followed the WIKI correctly and send me any stack traces

**Comment by Derpydoo** [comment]
isDisplay is true, I followed the tutorials and the crates worked fine when I first made then a few weeks ago. Seems something broke them but I can't figure out what. The only thing I've changed is adding Luckperms and setting the permissions for anyone to use them. 

I may need to try uninstalling the plugin and reinstalling. Maybe a server reset down the line caused a corruption.

**Comment by ABravePanda** [comment]
The problem is that is display is true. You only want to set that true if the item is a display only item.

**Comment by Derpydoo** [comment]
Oh! I see! OK I'll give that a go tomorrow and see what happens.
________________________________
