### ISSUE TITLE
Upon setting Loot Crate knockback value too high it can potentially crash the server

### ISSUE THREAD

**Issue by SpencerLommel** [ABravePanda/LootCrate#54]
### Steps to reproduce

1. "/lootcrate option 117"  (replace 117 with crate ID)
2. Click netherite sword (knockback level)
3.  Type in high value (In my case 10000000)
4. Left click on crate without key to enact knockback

I have attached a snippet of my log file to this Issue Request

### Possible Fixes

1. Set maximum value on knockback amount

I am going to make a fork of this repo and implement this fix so it can be merged into the main branch and eventually updated on Spigot :)

Great plugin but a few bugs that could be ironed out!

### Crash Log
[LootCratesErrorLog.log](https://github.com/ABravePanda/LootCrate/files/14135088/LootCratesErrorLog.log)

**Comment by ABravePanda** [comment]
funnily enough, my i actually have this fix in a pending commit :)
