### ISSUE TITLE
can not open crate even with permissions. 1.16.5

### ISSUE THREAD

**Issue by GalaxyRoma** [ABravePanda/LootCrate#59]
players can not open the crate. even with the right permissions. they right click and nuthing at all happens but they can left click to look, pls help

**Comment by ABravePanda** [comment]
Is your spawn protection off / are you in a world spawn?

**Comment by GalaxyRoma** [comment]
now I have disabled it and I see that it works, thank you

lun., 3 iun. 2024, 02:53 ABravePanda ***@***.***> a scris:

**Comment by ABravePanda** [comment]
Glad to hear it!
