### ISSUE TITLE
Rewards cant stack

### ISSUE THREAD

**Issue by ABravePanda** [ABravePanda/LootCrate#7]
Reward cannot stack with their vanilla counterpart.

**Comment by MadeBySaints** [comment]
I believe this is directly related to this issue and the issue we spoke about a few days ago. The NBT data added to items from lootcrate is causing this error, and is why their counterparts are not stacking
![image](https://user-images.githubusercontent.com/3265397/106854127-c6185180-6688-11eb-83f7-9fc98eb0bab1.png)

**Comment by ABravePanda** [comment]
Currently looking to see if i can replicate this bug, if so I will comment again.

**Comment by ABravePanda** [comment]
Issue should be fixed.
